language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - setup=basic
    - APP_ENV=production
    - APP_DEBUG=true
    - DB_DATABASE=emoji
    - DB_HOST=localhost
    - DB_USERNAME=postgres
    - DB_PASSWORD=postgres
    - DRIVER=pgsql
matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm

install: travis_retry composer install --no-interaction

script: vendor/bin/phpunit
